### PR TITLE
feat: add music plugin

### PR DESCRIPTION
**Pull request by mamal72**
Music search and download plugin implemented.
music

### CODE REVIEW

**Comment by piguet** [comment]
unable to make it work.. Do I need the latest tg client?

**Comment by rockneurotiko** [comment]
@piguet you have to install htmlparser in luarocks

**Comment by yagop** [comment]
I was looking for a (better) API and haven’t found. There should be, becasue many Android apps communicate with them. Someone with JSON would be great.

**Comment by mamal72** [comment]
@yagop I didn't found any better one. This is the best reference AFAIK.

**Comment by Akamaru** [comment]
Installed htmlparser, but it does'nt work
*** lua: plugins/music.lua:45: attempt to call global 'unescape_html' (a nil value)

**Comment by Akamaru** [comment]
oh my bad
forget to add function unescape_html(str) to utils.lua ^^

**Comment by piguet** [comment]
I am sorry, but how can I install htmlparser? luarocks install htmlparser from command line doesn't seem to work

**Comment by siyanew** [comment]
when i load this plugin this error shown: 
>error loading module 'htmlparser.ElementNode' from file '.luarocks/share/lua/5.2/htmlparser/ElementNode.lua':
>        .luarocks/share/lua/5.2/htmlparser/ElementNode.lua:141: '=' expected near 'nextpart'

**Pull request closed without merging**
