### PR TITLE
Add a calculator plugin

### PR DESCRIPTION
**Pull request by ollpu**
This plugin calculates mathematical expressions using Lua's load() function.
Just doing this has a couple issues:
 - User of the command now has privileges to execute _any_ lua command
 - To access mathematical functions & constants, the user would need to use math.function()/constant

To go around this, I made the plugin replace all words in the expression with math.word. This should take care of both of the issues above.

### CODE REVIEW

**Comment by yagop** [comment]
How about something like:
```lua
patterns = {
  "^!calc  ([%w%+%-%*%(%)])+$"
},
```

**Comment by ollpu** [comment]
Allright,  changed. I modified your pattern a little, it now includes spaces (and also actually made it work :smile:);

`
^!calc ([%w%+%-%*%(%) ]+)$
`

**Comment by ollpu** [comment]
Also, it might be useful to include the ^ symbol, rebasing that in, hold on...

**Comment by ollpu** [comment]
I just realised that division, decimal numbers and modulo (%) aren't supported either. I'll put these in the pattern when I have time today.

**Comment by ollpu** [comment]
There we go, let's hope that's all.

**Comment by yagop** [comment]
In order to avoid executing code I think the best way is to use an expression parser, there is a a cool implementation with LPeg (will include on project):

http://www.inf.puc-rio.br/~roberto/lpeg/#ex (Arithmetic expressions)

Sorry for the issues and time.

**Comment by ollpu** [comment]
No problems! I was looking for a parser like that, but couldn't really find one. But, the way it's used in the example you posted, makes me believe it doesn't really follow the order of operations, does it? And is it possible to still implement mathematical functions or constants? 

Anyways, I'll probably use the plugin the way it is now in my personal bot.

**Comment by yagop** [comment]
At the end api.mathjs.org is in use.

I don't like to use another HTTP API, but I think is better than evaluate user code. I was working with LPeg, its really powerfull but takes me much time to implement all the Lua functions . MathJS have a bunch of features.

http://mathjs.org/docs/reference/functions/categorical.html

**Comment by ollpu** [comment]
Seems good! I was actually looking for an API like that, but only found ones that were really bad.

Also by the way, there's a typo in the new plugin:

**Comment by yagop** [comment]
Thanks! solved.

**Pull request closed without merging**
