### PR TITLE
Added temperature plugin

### PR DESCRIPTION
**Pull request by Cotel**
For controlling Raspberry Pi temperature if you are hosting the bot on it like me.

### CODE REVIEW

**Comment by rockneurotiko** [comment]
Two things:
1. You are calling a command called `temperatura`, I don't think that this is a normal command in any linux (first, the name is in spanish, and usually *nix uses english, and second, in my raspberry don't exist that command xD)
2. You have `run_command` function in utils that you can use. [link](https://github.com/yagop/telegram-bot/blob/master/bot/utils.lua#L143), so the function can be (handling the error):
```lua
local function run(msg, matches)
    local res = run_command(/opt/vc/bin/vcgencmd measure_temp) or 'An error happened'
    return res
end
```

Ok, while I was reading, I saw that you updated the command with a new commit, nevermind 1 xD

**Comment by rockneurotiko** [comment]
Also, the pattern in english ;-)

**Comment by Cotel** [comment]
I have fixed what you have said. Thank you for the help, I don't know Lua and I made this from the echo plugin :D

**Comment by DevPGSV** [comment]
@Cotel , all I konw about lua is what I learned from the plugins (and from investigation to make plugins). And.... To do my first plugin, I duplicated echo.lua and modified it.

So.... you chosed a good starting point :+1:

**Comment by Wawoul** [comment]
Just a quick note for anyone having the "VCHI Initialization failed" error when running the command as i did. You need to be in group "video" so that vcgencmd can access /dev/vchiq. But "cat /sys/class/thermal/thermal_zone0/temp" requires no privileges.

Solution: sudo usermod -G video *yourloginname*

Neat plugin tho, thanks!

**Comment by yagop** [comment]
Despite is a good idea and nice plugin. There is no general usage for other linux distros.

**Pull request closed without merging**
