### PR TITLE
Fixing stats to show the result sorted by messages

### PR DESCRIPTION
**Pull request by but3k4**
I'm using your project and me and a friend did a simple modification on stats plugin to show the result sorted by messages

### CODE REVIEW

**Comment by yagop** [comment]
` plugins/edbot.lua` ?

**Comment by but3k4** [comment]
Edbot.lua is a brazilian ai, its answers are in portuguese, because that i
didnt include this plugin on pull request.

**Comment by yagop** [comment]
You are pull requesting 2 paths. https://github.com/but3k4/telegram-bot/commit/3caf15531f8258f3184b27b2fb242108c75f4721 contains traffic and edbot plugins

**Comment by but3k4** [comment]
I'm sorry, If you want to include them ok, but they will answer in
portuguese. If not please, reject the pull request and I will do another
one.

**Comment by yagop** [comment]
No problem. Ok, I close it.

**Pull request closed without merging**
