### PR TITLE
Autoanswer

### PR DESCRIPTION
**Pull request by sempiternum**
This pull request adds two plugins:

-AutoAnswers.lua that enables the user to specify keyword and answers of the bot

-MentionNotifier.lua that enables the user to receive PMs from bot in case someone mentions specified keywords.

### CODE REVIEW

**Comment by HKraToS** [comment]
thanks to your code, but how can make a Exception to " ! " in patterns ?

**Comment by yagop** [comment]
Indentation?

**Comment by sempiternum** [comment]
From: HKraToS
>but how can make a Exception to " ! " in patterns ?

you mean that you want to exclude bot answers and/or notifications in the case that you're writing something like "!command containing one of your hotkeys"? 

in that case, you have to modify the if statements to esclude possible "!commands".

Otherwise, if your request was knowing if there are some !commands associated with my plugins, a part from disable and enable plugin, no, there is no commands. you've to edit the plugin lua file to add and associate keywords to answers etc.

**Comment by sempiternum** [comment]
From: yagop
>Indentation?

were you referring to me?

**Comment by yagop** [comment]
There are some files without indentation. Other uses tabulation.

**Comment by sempiternum** [comment]
Yeah i know, i deleted all pull request for the moment, i made a lot of confusion with branches and stuff.

**Pull request closed without merging**
