### PR TITLE
Plugin to make a screenshot of a web.

### PR DESCRIPTION
**Pull request by rockneurotiko**

### CODE REVIEW

**Comment by Walkman100** [comment]
This PR includes the URL expander plugin? Maybe you should rebase the commits...

**Comment by rockneurotiko** [comment]
Oh damn, I was doing 3 PR at the time, not all can go good XD

Thanks!!

**Comment by rockneurotiko** [comment]
Removed the commit.
Thanks again!

**Comment by Walkman100** [comment]
:+1:

**Pull request merged**
