### PR TITLE
Feature/plugin/face

### PR DESCRIPTION
**Pull request by DevPGSV**
A plugin just for fun! not very useful, it sometimes has some errors... (well, the api has some errors XD).
But, .... it does well its job.

Examples with some photos from Google Images:

captura
captura1
captura2
captura3

### CODE REVIEW

**Comment by DevPGSV** [comment]
https://github.com/yagop/telegram-bot/pull/223#issuecomment-108883259

**Comment by yagop** [comment]
ab2a5d2cabe1db85e1d3971f2fb51ae525e873e8 Tested and working perfectly
captura de pantalla de 2015-06-07 15 09 44

**Comment by Akamaru** [comment]
Does'nt work for me
Got everytime "There was an error. #432"
I used your key and my key, but it does'nt work :/
image
Any ideas?

**Comment by DevPGSV** [comment]
Perhaps the image is too big, so the api can't process it.
Ot perhaps the key doesn't have permission to that app....

You can try it here:

https://www.mashape.com/faceplusplus/faceplusplus-face-detection

Check if it works there.

**Pull request merged**
