### PR TITLE
Update and rename bot/bot.lua to ربات/bot.lua

### PR DESCRIPTION
**Pull request by ALIATAEE**
sudo apt-get install libread line-dev libssl-dev lua5.2
liblua5.2-dev libevent-dev make unzip get redis-server g++ libjansson-
dev libpython-dev expat libexpat1-dev

### CODE REVIEW

**Comment by rockneurotiko** [comment]
Is this a joke?

**Comment by ALIATAEE** [comment]
git Clone Https://githun.com/seed Team/teleseed.git

**Comment by ALIATAEE** [comment]
Cd Teleseed

**Comment by ALIATAEE** [comment]
Chmod +X Launch.sh

**Comment by ALIATAEE** [comment]
Launch.sh Install/.

**Comment by rockneurotiko** [comment]
So hilarious xD

**Comment by yagop** [comment]
I blocked the user.

**Pull request closed without merging**
