### PR TITLE
Added yoda plugin

### PR DESCRIPTION
**Pull request by DevPGSV**
captura
captura2
captura

### CODE REVIEW

**Comment by yagop** [comment]
Are you sure about exposing the `X-Mashape-Key`?

**Comment by DevPGSV** [comment]
Yeah. I mean, it's not mine, its public XD

**Comment by DevPGSV** [comment]
Alright, I checked, and for some reason now it doesnt work with that X-Mashape-Key. Perhaps too many queries. :(

The same happens for #224

**Comment by DevPGSV** [comment]
I checked and now, for some reason, it doesn't work with that X-Mashape-Key. Perhaps too many requests :(
The same applies to #224 ...

**Comment by bb010g** [comment]
Perhaps load the key from a separate file, like what was done with the Twitter API keys?

**Comment by DevPGSV** [comment]
That would be a great idea. And... as several plugins use this key.... it could be shared :)

If no one implements it, I'll do it (I can right now, lets see if I have time tomorrow)

**Pull request merged**
