### PR TITLE
Plugin for converting LaTeX equation into image

### PR DESCRIPTION
**Pull request by ypcat**
Example usage:

    !tex \sum_{i=1}^{n} x_{i}^{2}

### CODE REVIEW

**Comment by rockneurotiko** [comment]
OMG I love it! :-)

Just two questions:
1- The image could be larger? now are a little bit little (Maybe the API have some size option?)
captura de pantalla de 2015-05-20 13 45 28
2- Can you squash the "add tex plugin" and "description" commits in one? In that way is easier to see the commit where it was added the plugin at first :)

P.S: I love that you can send anything!

captura de pantalla de 2015-05-20 13 50 39

**Comment by ypcat** [comment]
@rockneurotiko this is from an external service http://latex.codecogs.com/
I'm not sure if it can support size option.
And I think I should try to respect their usage policy.

**Comment by ypcat** [comment]
@rockneurotiko I figure out how to adjust size.

As for usage policy, according to http://www.codecogs.com/latex/usage.php they request link back for free usage.
Here is my idea: we can append a link after the generated image like:



However, telegram will automatically extract the summary from any link, which is quite annoying. Do you know how to disable this behavior from bot API?

**Comment by ypcat** [comment]
I screwed up my branch while squashing commits, I will start over with another branch.

**Comment by ypcat** [comment]
deprecated by https://github.com/yagop/telegram-bot/pull/177

**Comment by psykomantis** [comment]
oh god I was thinking to do this plugin :( it seems that developers often have same ideas

**Pull request closed without merging**
